### ISSUE TITLE
Periodic disconnect/reconnect issue

### ISSUE THREAD

**Issue by BunkerSquirr31** [sctanf/picoamp#3]
I've noticed that when there is no audio input, the amp will start to "boot loop," disconnecting and reconnecting to the host device every 5-6 seconds. Each disconnect/reconnect cycle is accompanied by a small audible clicking noise. I've been able to repeat this behavior using  different USB ports, different cables, different Pico boards, and on different platforms (Windows, MacOS and iOS).

**Comment by Sho0Fly** [comment]
Have you tried updating to v7? Fixes the boot loop issue I was having. 

Currently there is a bug with Windows 10/11 and the Pico Amp causing issues with the driver not innitializing. If you run into that, the temp fix is to go into, "Device Manager", uninstall the "Pico Amp" driver, then go to the top where it says, "Action" and select, "Scan for Hardware changes".

Should auto fix itself after that. Just be aware disconnecting the device may cause this particular bug again and you'll have to repeat the process until a fix is pushed on GitHub.

**Comment by BunkerSquirr31** [comment]
Yep, looks like v7 did the trick. Had my Github client configured wrong and wasn't pulling the latest build. thanks!
